databases:
  - name: Face_Recognition
    databaseName: Face_Recognition
    user: Face_Recognition

services:
  - type: web
    name: Face_Recognition
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Face_Recognition.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Face_Recognition
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4